### ISSUE TITLE
Failed to import transformers.models.phi3.configuration_phi3 because of the following error (look up to see its traceback): No module named 'transformers.models.phi3.configuration_phi3'

### ISSUE THREAD

**Issue by hkapavarapu** [1038lab/ComfyUI-OmniGen#33]
2024-11-24T23:34:44.560623 - OmniGen models verified successfully2024-11-24T23:34:44.560623 - 
2024-11-24T23:34:44.563624 - !!! Exception during processing !!! Failed to import transformers.models.phi3.configuration_phi3 because of the following error (look up to see its traceback):
No module named 'transformers.models.phi3.configuration_phi3'
2024-11-24T23:34:44.564671 - Traceback (most recent call last):
  File "C:\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1778, in _get_module
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models.phi3.configuration_phi3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\execution.py", line 289, in execute
    obj = class_def()
          ^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\ailab_OmniGen.py", line 53, in __init__
    from OmniGen import OmniGenPipeline
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\OmniGen\__init__.py", line 1, in <module>
    from .model import OmniGen
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\OmniGen\model.py", line 14, in <module>
    from OmniGen.transformer import Phi3Config, Phi3Transformer
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\OmniGen\transformer.py", line 18, in <module>
    from transformers import Phi3Config, Phi3Model
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1767, in __getattr__
  File "C:\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1766, in __getattr__
  File "C:\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1780, in _get_module
RuntimeError: Failed to import transformers.models.phi3.configuration_phi3 because of the following error (look up to see its traceback):
No module named 'transformers.models.phi3.configuration_phi3'

**Comment by Marcihuppi** [comment]
same here
